### ISSUE TITLE
Cannot insert new MyAccount Tab with Override

### ISSUE THREAD

**Issue by soumitra25912** [scandipwa/scandipwa#2871] opened 2021-07-12 13:29 UTC
**Description**:
Cannot insert new MyAccount Tab with Override

**Expected behavior**:
A new tab with custom content will be created under MyAccount

**To Reproduce**:
https://docs.scandipwa.com/tutorials/customizing-your-theme/customizing-javascript/adding-a-section-in-my-account

**Versions**:
- ScandiPWA: 4.5.1

**Additional context**:

**Comment by Elena-Evsa** [comment] 2022-09-02 07:35
Closing after communication with developer as not actual

**Closed by Elena-Evsa** 2022-09-02 07:35 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, Area: My account

**Comment by infinityredux** [comment] 2022-09-02 10:25
@Elena-Evsa can you clarify "as not actual"? I assume you mean not a bug? Or if the discussion was public, can you point to where it took place for further context?

**Comment by Elena-Evsa** [comment] 2022-09-02 10:40
Comment from developer: now we're migrating to 'typescript' and after release issue will be not actual. If not, the issue can be reopened

**Comment by infinityredux** [comment] 2022-09-02 10:41
Ah, thank you.
