### ISSUE TITLE
Can´t build ScandiPWA v5.3.2

### ISSUE THREAD

**Issue by tim-breitenstein-it** [scandipwa/scandipwa#5135] opened 2022-08-10 06:49 UTC
**Steps to reproduce:**
1. Update ScandiPWA from v5.3.1 to v5.3.2
  - Update `package.json`
  - Update `composer.json`
  - Run: `composer update`
  - Run: `npm update`
2. Run: `BUILD_MODE=magento npm run build`

**Actual result**

```
tim@mage2-test:/var/www/tim/magento-2-4-4-scandipwa/src/localmodules/magento-itb$ BUILD_MODE=magento npm run build

> magento-itb@5.3.2 build
> scandipwa-scripts build


ERROR!

     Composer module required is conflicting with requested module versions.
     Please update scandipwa/quote-graphql version to 3.0.3.


NOTE!

     The 3.0.3 version is the minimum requested version.
     Update it at you own risk! The version of choice must meet following constraints: 3.0.3!


```

**Expected result**
Successfully build ScandiPWA

**Testing details**
**Screenshot/Screencast**
If applicable, add screenshots or screen-capture to help explain your problem. If you would like to share logs - please use [fenced code blocks](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

**Versions**
- ScandiPWA: v5.3.2
- Magento: v2.4.4

**Additional context**

The [v5.3.2 Release Changelog](https://github.com/scandipwa/scandipwa/releases/tag/%40scandipwa%2Fscandipwa%405.3.2) says: 

> Composer dependencies:
> [...]
> scandipwa/quote-graphql: from 2.19.26 to 3.0.4
> [...]

But the v5.3.2 [package.json](https://github.com/scandipwa/scandipwa/blob/%40scandipwa/scandipwa%405.3.2/packages/scandipwa/package.json):

```
[...]
    "composer": {
            [...]
            "scandipwa/quote-graphql": "3.0.3",
            [...]
```

```
tim@mage2-test:/var/www/tim/magento-2-4-4-scandipwa$ composer info scandipwa/quote-graphql
name     : scandipwa/quote-graphql
descrip. : N/A
keywords :
versions : * 3.0.4
type     : magento2-module
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
homepage :
source   : [git] https://github.com/scandipwa/quote-graphql.git 53718f18c76d05069662964e8cc2c3ef5ba8e2d4
dist     : [zip] https://api.github.com/repos/scandipwa/quote-graphql/zipball/53718f18c76d05069662964e8cc2c3ef5ba8e2d4 53718f18c76d05069662964e8cc2c3ef5ba8e2d4
path     : /var/www/tim/magento-2-4-4-scandipwa/vendor/scandipwa/quote-graphql
names    : scandipwa/quote-graphql

support
source : https://github.com/scandipwa/quote-graphql/tree/3.0.4

autoload
files
psr-4
ScandiPWA\QuoteGraphQl\ => src

requires
magento/framework *
magento/module-authorization *
magento/module-bundle *
magento/module-bundle-graph-ql ^100.3
magento/module-catalog-rule *
magento/module-checkout *
magento/module-customer *
magento/module-integration *
magento/module-inventory-configuration-api *
magento/module-inventory-reservations-api *
magento/module-inventory-sales-api *
magento/module-quote *
magento/module-quote-graph-ql ^100.3
magento/module-sales *
magento/module-webapi *
scandipwa/performance ^1.0
```

**Comment by zans-laksa** [comment] 2022-08-10 12:17
Fixed here https://github.com/scandipwa/scandipwa/commit/74a32a2caf738cf7bed1255d46699f5826f31cfa
The issue is fixed in the v5.3.3

**Closed by zans-laksa** 2022-08-10 12:17 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
