### ISSUE TITLE
system redirect into "Something went Wrong" Page

### ISSUE THREAD

**Issue by AprilNJ** [scandipwa/scandipwa#5022] opened 2022-07-12 09:24 UTC
[](url)[](url)> > thanks i update reproduce again
> 
> We tested on our master and couldn't replicate it. We will update the demo sites (production) and test on them. Also, if you could send us a video, it will help a lo

https://user-images.githubusercontent.com/108717422/178457504-124ee22c-4a54-4441-8a55-9f32e86cfefc.mov

t :D

_Originally posted by @AprilNJ in https://github.com/scandipwa/scandipwa/issues/5003#issuecomment-1181525780_

**Comment by carinadues** [comment] 2022-07-12 12:03
Hi, @AprilNJ can you share the link to this website please?

**Comment by aleksandrakorolova** [comment] 2022-09-06 07:14
Hello @AprilNJ!
Please, notify us if bug still is actual and if yes, please provide additional information about it. For now we are closing tasks because can’t reproduce

**Closed by aleksandrakorolova** 2022-09-06 07:14 UTC
