### ISSUE TITLE
Filters are inconsistent on the search page

### ISSUE THREAD

**Issue by jayankaghosh** [scandipwa/scandipwa#3380] opened 2021-09-23 16:02 UTC
**Description**:
Visiting on a search page directly results in layered navigation not being shown. But visiting a search page AFTER visiting a category page results in the layered navigation being shows

**Expected behavior**:
The layered navigation should be visible whenever we visit the search page

**To Reproduce**:
1. Go to https://luma-demo.scandipwa.com/
2. Search for "women"
3. Layered navigation not present
4. Click on any one of the categories from the menu without refreshing the page
5. Search for "women"
6. Now layered navigation is displayed

**Versions**:
- ScandiPWA: 5.0.5
- Magento: 2.4.2-p2

NOTE:
It could have something to do with the `is_anchor` value passed to `CategoryFilterOverlay` on `Component/CategoryPage/CategoryPage.component`
For the search page, it is `undefined` initially but is `1` after we've visited any category page. I tried hardcoding it to `1` if it is `undefined`, but that resulted in `TypeError: Cannot read property 'map' of undefined in CategoryConfigurableAttributes_ (at CategoryConfigurableAttributes.container.js:64)` and hence I didn't deep-dive further into it

**Comment by aleksandrakorolova** [comment] 2021-09-24 09:17
Closing as duplicate of #2934

**Closed by aleksandrakorolova** 2021-09-24 09:17 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
