### ISSUE TITLE
No placeholder in select after selected option is deselected

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3817] opened 2021-11-24 18:10 UTC
**To Reproduce**:
1. Go to http://scandipwapmrev.indvp.com/default/baggini-bagpack-108.html
2. Select `Medium` size in dropdown
3. Click on `Choose size...` to deselect selected option

**Result:**
No placeholder:
<img width="350" alt="Baggini Bagpack 108 2021-11-24 18-09-32" src="https://user-images.githubusercontent.com/79456428/143292335-ed623087-9972-4db1-a1f2-c59654b5730b.png">

**Expected result:**
`Choose size...` placeholder is displayed:
<img width="341" alt="Baggini Bagpack 108 2021-11-24 18-09-06" src="https://user-images.githubusercontent.com/79456428/143292296-00238b60-0f01-4116-84f8-b85414c06247.png">

**Comment by aleksandrakorolova** [comment] 2021-11-30 06:30
Duplicate of #3692

**Closed by aleksandrakorolova** 2021-11-30 06:30 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, FE
