### ISSUE TITLE
Issues connected with price filter

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1864] opened 2020-12-11 12:25 UTC
**1. Description**:
Not all products displayed belong to the specific price step that is selected.

**Expected behavior**:
Only the products with the price between the range selected should be displayed.

**To Reproduce**:
1. Open dresses category - https://scandipwapmrev.indvp.com/default/women/women-dresses
2. Select price filter from 0 to 20
3. Check the price of the items - some are higher than 20.

**Actual result**:
Products with price $130 are displayed
https://scandipwapmrev.indvp.com/default/women/women-dresses?customFilters=price:0_50
![image](https://user-images.githubusercontent.com/73526235/101901532-d4cb1680-3bb9-11eb-86b9-26c7e6d58403.png)

______________________________________________________________________________________________________________________________________

**2. Description**:
Price filter has one step - from $0.00 to $20.00

**Expected behavior**:
The price steps should respect the configurations for the Default Price Navigation Step and Maximum Number of Price Intervals and include all products.

**To Reproduce**:
1. Open category sunglasses - https://scandipwapmrev.indvp.com/default/accessories/accessories-sunglasses

**Actual result**:
The price filter has one step - from $0.00 to $20.00, but the glasses cost more than that.
![image](https://user-images.githubusercontent.com/82165392/118702114-e3fa6400-b7ea-11eb-8320-e8b62ff18a06.png)

______________________________________________________________________________________________________________________________________

**3. Description**:
Items shown after selecting the price range don't have the selected price.

**Expected behavior**:
All of the items should have the price in between the selected range.

**To Reproduce**:
1. Open category bags - https://scandipwapmrev.indvp.com/default/accessories/bags
2. Filter by price.
3. Check the products prices.

**Actual result**:
https://drive.google.com/file/d/1MZ6Z_1uLHVM2NU5Xpu-zLYLrHylEyQjQ/view?usp=sharing
______________________________________________________________________________________________________________________________________

**4. Description**:
The selected price range is shown with the checkbox unselected, and when the user clicks on it, there is either an error or it goes back to the previous filter.

**Expected behavior**:
The checkbox should be selected. No errors should occur.

**To Reproduce**:
1. Open category bags - https://scandipwapmrev.indvp.com/default/accessories/bags
2. Filter by price twice.
3. Check the product prices.

**Actual result**:
https://drive.google.com/drive/folders/1g4teAxHdfSnqz3zdHrT4Gmq3xQbjtHrk

**Comment by tatiana-scandi** [comment] 2021-08-04 09:03
I found a new issue:

Price navigation step is shown in EUR, if selected currency is USD.

Preconditions: currency rate USD to EUR = 1.3, Layered navigation setup:
<img width="992" alt="Configuration : Settings : Stores : Pre Magento Admin Suff 2021-08-04 09-54-42" src="https://user-images.githubusercontent.com/79456428/128152578-cfa6a90f-e995-4a9e-8a86-d069fc669aa8.png">

How to reproduce:
1. Switch to USD
2. Open category
2. Apply price filter

Result: Initial interval is 39 USD = 30 EUR (which is correct). When filter is applied, intervals change to 30 USD.

Expected result: Intervals don't change, when filter is applied (they are always equal to 39 USD).


https://user-images.githubusercontent.com/79456428/128152973-16ff43d5-12a7-474d-9cf2-29c37e030d84.mp4

**Comment by aleksandrakorolova** [comment] 2021-08-04 09:07
@tatiana-scandi Task for this issue was created #2991

**Comment by tatiana-scandi** [comment] 2021-08-04 17:10
Issue 4: I fixed it already several months ago.
Also I was not able to easily reproduce issues 1 to 3 (there were multiple fixes for layered navigation + magento modules have been updated since Dec 2020). Please, recheck if we still have the problems mentioned after https://github.com/scandipwa/catalog-graphql/pull/114 is merged.

**Comment by carinadues** [comment] 2021-08-17 12:34
https://github.com/scandipwa/catalog-graphql/pull/114 is merged :)

**Comment by Elena-Evsa** [comment] 2021-09-13 09:50
1. Can reproduce
![image](https://user-images.githubusercontent.com/84388061/132855662-2d36a14c-235f-4bfe-9726-dedcfc436146.png)
2. Can not reproduce
3. Can not reproduce
4. Can not reproduce
5. Bug from comment fixed in #2991

**Closed** 2021-09-22 15:11 UTC
Labels: Type: bug, Core, Status: Failed QA, Area: Price, Area: PLP
