### ISSUE TITLE
Position of attribute values is not respected on the front-end

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#1420] opened 2020-10-13 13:44 UTC
**Description**:
Position of attribute values is not respected on the front-end

**Expected behavior**:
Position of attribute values is respected on the front-end PLP (layered navigation) and PDP 

**To Reproduce**:
1. Open admin->stores->attributes->products
2. Open any attribute that is filterable 
3. Change the position of attribute values
4. Save and clear cache
5. Open PLP
6. Notice the position is not respected
7. Open PDP (config products that have such attribute)
8. Notice the position is not respected

**Comment by magexpert** [comment] 2020-10-15 07:07
We have same issue. Change position have not effect in front-end. Should be fixed.

**Comment by tatiana-scandi** [comment] 2021-04-05 12:22
Looks like a duplicate to this one: https://github.com/scandipwa/scandipwa/issues/1534

**Comment by aleksandrakorolova** [comment] 2021-09-15 11:48
Closed task because can't reproduce

**Closed by aleksandrakorolova** 2021-09-15 11:48 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
