### ISSUE TITLE
Category filter Price and Category is not translated

### ISSUE THREAD

**Issue by jari646** [scandipwa/scandipwa#1348] opened 2020-09-30 06:21 UTC
**Description**:
When I use different language than English, category page filter heading Price and Category will not be translated even I put these into translation files.

**Versions**:
- ScandiPWA: 3.x-stable
- Magento 2.3.5

**Comment by franconicolasocchi** [comment] 2021-06-22 06:29
Same here
ScandiPWA 4.4.0
Magento 2.4.2

**Comment by carinadues** [comment] 2021-07-18 22:19
Closing as a duplicate of https://github.com/scandipwa/scandipwa/issues/2562

**Closed by carinadues** 2021-07-18 22:19 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
