### ISSUE TITLE
Product is missing on PLP if user added it for category in Admin panel

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4353] opened 2022-02-28 09:34 UTC
**Description**:
Product is missing on PLP if user added it for category in Admin panel

**Expected behavior**:
Product Y is displayed on PLP

**To Reproduce**:
**FE:**
1. Open PLP for category X

**Admin panel:**
1. Open Admin panel -> Catalog -> Category X
2. Add product Y to the category
3. Save

**FE:**
2. Refresh PLP for category X

**Actual result**:
Product Y is missing 
Return wrong data
![Screenshot 2022-02-28 at 11 33 40](https://user-images.githubusercontent.com/73526235/155959387-9053d257-d8be-497c-8e7a-3e99ffb08a1a.png)

**Additional context**:
Connected with cache

**Comment by leonazava** [comment] 2022-04-18 11:02
The issue was caused by ElasticSearch not writing new product indexes on PMrev. It's fixed now, the issue can be closed.

**Comment by Elena-Evsa** [comment] 2022-04-26 11:22
Products are not shown on PLP without cache flush

**Comment by aleksandrakorolova** [comment] 2022-05-12 09:59
After fixing need to check this issue #2473 because now can reproduce it

**Closed** 2022-05-12 10:40 UTC
Labels: Type: bug, Core, High Priority, Status: Failed QA, Area: PLP
