### ISSUE TITLE
Wrong product price for simple product with required customization if product has a special price

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2674] opened 2021-05-26 06:43 UTC
**Description**:
Wrong product price for simple product with required customization if product has a special price

**Expected behavior**:
Product price - 15
![image](https://user-images.githubusercontent.com/73526235/119476071-625c8600-bd56-11eb-96a0-e76154f02aed.png)

**To Reproduce**:
1. Open simple product with required customization option and product should have a special price - https://master.d25kd40decjpue.amplifyapp.com/default/special-product.html

**Actual result:**:
Product price - 15.75 (Special price + min option price)
![image](https://user-images.githubusercontent.com/73526235/119476058-5f619580-bd56-11eb-9280-0b9010a77514.png)
![image](https://user-images.githubusercontent.com/73526235/119614043-7d86ce80-be06-11eb-8ce4-ad7ef007923d.png)

**Additional context**:
Original price - 20
Special price - 15

**Comment by tatiana-scandi** [comment] 2021-06-22 22:07
FE: https://github.com/scandipwa/scandipwa/issues/2674
BE: I investigated the issue and wanted to apply the fix by myself, but noticed the same fix was already done by contributor: https://github.com/scandipwa/performance/pull/19. I tested it locally, it helps to resolve the issue.

Behaviour after fix: 
- product is displayed as Out of stock, which is correct
- Label As low as is hidden for out of stock products (done for the following reasons: 1. Luma does it 2. it makes sense, as lowest price in not applicable, if all options are Out of stock) 3. this is default Magento behaviour to return 0 for minimum price, if all options are out of stock
- also disabled Add to cart button for Out of stock products

Asked Carina to confirm this is fine before implementing it like this.

**Comment by tatiana-scandi** [comment] 2021-06-24 15:42
BE PR: https://github.com/scandipwa/catalog-graphql/pull/105
FE PR: https://github.com/scandipwa/scandipwa/pull/2807

Changes made: 
- BE:-calculate before and after tax prices for simple product with customizable options instead of showing value set up in admin (which could be either before or after tax depending on Magento settings + doesn’t include discount)
- BE: add calculation of simple product price initial price (i.e. when none of the options is selected). the value we showed before was incorrect, as it showed min price of product, when least expensive required options are selected
- BE: adjust bundle options prices calculation to work fine both for “catalog prices: including tax” and " “catalog prices: excluding tax”
- FE: change logic for customizable options prices display based on BE changes so that it shows correct prices
- FE: change logic for summing up base product price with option prices, so that 3 prices are calculated as expected 1. old price 2. current price 3. current price excl. tax  
- FE: add logic for adding up customizable option prices for product types other than simple (there was an error in logic that for other product types adding up options step was skipped => I split it into 2 steps: first, add up selected variants; second, add up customizable options).

**Comment by carinadues** [comment] 2021-06-28 13:27
@aleksandrakorolova please QA and close if it's ok

**Comment by aleksandrakorolova** [comment] 2021-06-29 09:08
1. Still can reproduce issue on PLP - wrong price incl. and excl. tax:
![Screenshot 2021-06-29 at 07 46 20](https://user-images.githubusercontent.com/73526235/123741180-464a8800-d8b2-11eb-8c74-b0fb51a9af82.png)
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/cardigan-in-brown.html
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/special-product.html

2. Wrong price excl. tax = excl. tax + min option price excl tax
![Screenshot 2021-06-29 at 08 30 51](https://user-images.githubusercontent.com/73526235/123742835-ffaa5d00-d8b4-11eb-8585-5c5fbe7d8391.png)
**Expected result:**
![Screenshot 2021-06-29 at 08 30 57](https://user-images.githubusercontent.com/73526235/123742855-0933c500-d8b5-11eb-9a3d-c58dd307695d.png)
**Product:** 
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/flip-flops/havaianas-blue.html

**Comment by tatiana-scandi** [comment] 2021-06-29 16:23
Issue 1: Wrong price incl tax on PLP - fixed in https://github.com/scandipwa/scandipwa/pull/2817
Issue 2: Wrong percentage value on PDP for customizable option type percent (e.g. https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/kids/special-product.html). Cannot reproduce on local Magento and fix, as have no idea why prices are increased by 30%.
Issue 3: Min Price after selecting options is shown on PDP instead on base price before selecting options for virtual product. Fixed in https://github.com/scandipwa/scandipwa/pull/2817

**Comment by aleksandrakorolova** [comment] 2021-06-30 06:30
@tatiana-scandi 
2. I supposed, It's happening because of base currency EUR but default display currency USD. And percent is converted as EUR to USD. 
I created new task for this issue #2819

**Comment by carinadues** [comment] 2021-06-30 16:16
Closed after merging PR 2817

**Closed by carinadues** 2021-06-30 16:16 UTC
Labels: Core, Status: Failed QA, Type: bug

**Comment by aleksandrakorolova** [comment] 2021-07-01 10:57
Now Price without the required option is displayed on PDP

On PLP:
- Simple and virtual product:  price = product price + min required option price
- Config and downloadable product - the same price is displayed as on PDP

I will create a new task for issues on PLP
