### ISSUE TITLE
Old Price is not showing in PDP

### ISSUE THREAD

**Issue by jithutj** [scandipwa/scandipwa#2600] opened 2021-05-11 06:15 UTC
**Description**:
In PLP the Old Price is showing if product has special price, but in PDP it is only showing special price and not showing old price along with it...

**Expected behavior**:
Special Price and Regular price (old price) has to be displayed in PDP

**Screenshots, Video, Logs**
PLP - https://ibb.co/Y7F75ff
PDP - https://ibb.co/x8kzwVv

**To Reproduce**:
1. Go to 'https://tech-demo.scandipwa.com/smartphones-gadgets.html' link see there you can see the regular price that showing under the special price
2. Click on 'the product card' and goto pdp then you can see regular price is not visible.

**Versions**:
- ScandiPWA: 4.3

**Comment by aleksandrakorolova** [comment] 2021-05-11 07:07
Closing as duplicate of #2527

**Closed by aleksandrakorolova** 2021-05-11 07:07 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
