### ISSUE TITLE
 Contact Page (Mobile) Back Chevron Button is not working

### ISSUE THREAD

**Issue by EagleSH** [scandipwa/scandipwa#4667] opened 2022-04-06 15:49 UTC
On mobile if you go to the contact page and try to go back with top chevron button, nothing happens when you tap on it. 

the same issue is here also: https://tech-demo.scandipwa.com/contact

**Comment by aleksandrakorolova** [comment] 2022-04-07 05:37
Closed as duplicate of #3068

**Closed by aleksandrakorolova** 2022-04-07 05:37 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
