### ISSUE TITLE
Products are not loading correctly, random infinite loading

### ISSUE THREAD

**Issue by pysebb** [scandipwa/scandipwa#4737] opened 2022-04-26 08:20 UTC
**Description**:
There is a problem with loading products when trying to open multiple tabs. 
Sometimes this happens when entering a specific URL - Im having problems identifying the issue, because there is no error either in ScandiPWA or Magento.

Whenever you refresh the product - it loads correctly. But this happens daily to our live clients. 
This issue also persists in every ScandiPWA demo shop.

When product is that "loading" state - its not going to unfreeze itself, if the user does not reload the page.

**Expected behavior**:
I expect the product to load correctly and fully without a need to reload the product

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/2539735/165252500-cb2b1e5a-9c9e-4588-977d-981390001360.png)

https://user-images.githubusercontent.com/2539735/165254931-76fe0203-dc7a-4e3c-be78-68ad96b1f032.mp4

**Versions**:
- ScandiPWA: most likely it's latest 5.2.6 on https://tech-demo.scandipwa.com/
- ScandiPWA (my website): I've checked all 5.2.x versions
- Magento 2.4.3
- Any other composer module, you thing could be related
- This happens on every browser, chrome, firefox, safari, on mobile versions as well

**Comment by Elena-Evsa** [comment] 2022-04-26 09:15
Can reproduce only on demo website

**Comment by Ylmzef** [comment] 2022-05-03 00:09
https://github.com/scandipwa/scandipwa/issues/4513

**Comment by carinadues** [comment] 2022-05-19 22:26
Let's re-test after updating the demos with 5.2.7

**Comment by carinadues** [comment] 2022-05-24 10:39
I couldn't reproduce this one. @Elena-Evsa can you please try?

**Comment by AzizKHAN030** [comment] 2022-06-17 05:33
Might be fixed with #4892

**Comment by jbruni** [comment] 2022-06-30 12:21
Thanks, @AzizKHAN030 

We were having the exact same issue described here (our theme is based on version 5.2.6)

We applied code changes from #4892 and we got the issue fixed.

**Comment by carinadues** [comment] 2022-07-05 01:10
Closing the issue as it seems it was fixed by https://github.com/scandipwa/scandipwa/pull/4892. Let's test on the master and on the demos.

**Closed by carinadues** 2022-07-05 01:10 UTC
Labels: Type: bug, Demo, Core, Status: Waiting Estimate

**Comment by Elena-Evsa** [comment] 2022-07-06 13:50
Fixed by 4892
