### ISSUE TITLE
Bug that extends the lifetime of auth_token on FE while on BE token lifetime is unchanged.

### ISSUE THREAD

**Issue by edgarsbimbirulis** [scandipwa/scandipwa#3684] opened 2021-11-03 17:44 UTC
**Description**:
On every `isSignedIn` check auth_token is refreshed without BE part untouched or communication to it.
So when token is expired in BE, customer is not logged out because in browser token is still not expired due to constantly updating it with new `createdAt` value.
If in BE token is expired, when placing order error is thrown
`Guest checkout is not allowed. Register a customer account or login with existing one.`

**Expected behavior**:
Customer is logged out after set time in BE and in auth_token or communication with BE to refresh not only browser auth_token but also Magento token.

**To Reproduce**:
1. Log in to account
2. Navigate to any tab in My Account section
3. auth_token in Browsers Storage updating with createdAt value changing

**Versions**:
- used ScandiPWA version: 5.0.5

**Comment by aleksandrakorolova** [comment] 2021-11-04 06:23
Duplicate of #3486

**Closed** 2021-11-04 06:23 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
