### ISSUE TITLE
User isn't notified for automatically signing out after cookie lifetime expires and he/she refreshes the page

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2505] opened 2021-04-16 11:54 UTC
**Description**:
The user isn't notified for automatically signing out after the cookie lifetime expires if he/she refreshes the page. If the user is logged in and cookie lifetime expires and he changes the page within the website, he is notified about signing out. But if he refreshes the page, he doesn't get a notification.

**Expected behavior**:

User should get the following message when he was logged in and refreshes the page after the cookie lifetime expires:

![image](https://user-images.githubusercontent.com/82165392/115019358-7d9ec080-9e8f-11eb-91fb-ef4185aa17d1.png)

**To Reproduce**:
1. Open Admin panel -> Go to Stores -> Settings -> Configuration -> General -> Web
2. Open Default Cookie Settings section
3. Set 10 in Cookie lifetime (in seconds)
4. Save and Clear Cache
5. Go to Store and log in.
6. Wait 10 seconds.
7. Refresh the page.

**Actual result**:
The user isn't notified about being automatically signed out if he or she refreshes the page when this happens.

**Comment by Elena-Evsa** [comment] 2021-07-08 08:25
Still can be reproduced. Notification does not appear after refresh page

**Comment by winniepukki** [comment] 2021-07-13 13:16
The following feature implementation carries with a few minor unexpected bugs:
1. When the user visits the web page after a year of absence to purchase a new item, the 'You have been logged out' notification will be prompted, which is generally a strange behaviour
2. The code will contain many unnecessary checks since the storage resources will be increased
3. Implementing the feature will also carry with a few new unrevealed bugs that will only be fixed in the upcoming releases since it affects the sign-in / out functionality
4. Page reload is not a natural behaviour for the SPA

Closing the issue, considering the aforementioned cases after having a chat with @carinadues

**Closed by winniepukki** 2021-07-13 13:16 UTC
Labels: Core, Status: Failed QA, Type: bug
