### ISSUE TITLE
Issues related to DEMO websites

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3813] opened 2021-11-24 09:07 UTC
**Issue 1**: Icons from Follow section is not centered on 40skudemo
Appears on any store page (Germany, etc.)

**Expected behavior**:
Icons from Follow section is centered

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143206725-d888a490-02fb-4560-83b5-67097aba7c79.png)

**To Reproduce**:
1. Open Home page https://40kskudemo.scandipwa.com/default/ 
2. Scroll to footer

**Actual result**:
Icons from Follow section is not centered

---

**Issue 2**: If long description is empty then tab 'About' present on 40skudemo

**Expected behavior**:
If long description is empty then tab 'About' absent on PDP

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143207224-f332b300-94b7-455f-8e89-761b636f2a02.png)

**To Reproduce**:
1. Open https://40kskudemo.scandipwa.com/default/leitz-10120025-ring-binder-2-x-333826.html 

**Actual result**:
If long description is empty then tab 'About' absent on PDP

---

**Issue 3**: Shown empty section details on 40skudemo

**Expected behavior**:
If details absent then tab 'Details' absent on PDP

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/143207438-45597307-5c23-4f4f-84ea-1022b1c36563.png)

**To Reproduce**:
1. Open https://40kskudemo.scandipwa.com/default/leitz-hole-punch-10-sheets.html  

**Actual result**:
Shown empty section details on 40skudemo
 
---

**Issue 4**: 'Error fetching linked products' appear if user open product by link in steps on tech-demo

**Expected behavior**:
Error  does not appear if user open product by link in steps

**Screenshots, Video, Logs**
https://vimeo.com/647198439/431e8237e1

**To Reproduce**:
1. Open https://tech-demo.scandipwa.com/tech_storeview/product-13663.html

**Actual result**:
'Error fetching linked products' appear if user open product by link in steps on tech-demo

**Comment by tappiola** [comment] 2022-01-04 12:36
1. Fixed by changing cms contents.
2. Fixed in https://github.com/scandipwa/scandipwa/pull/4025
3. Fixed in https://github.com/scandipwa/scandipwa/pull/4025
4. Can't reproduce now. If manage to reproduce, please update issue description by adding full URL and body (if POST) for the request that returns an error.

**Closed** 2022-01-10 16:12 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, High Priority
