### ISSUE TITLE
Issues connected with authorization 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2568] opened 2021-04-30 07:12 UTC
**1. Description**:
Can't scroll page if user opens order in my account and Cookie Lifetime ends

**Expected behavior**:
Can scroll page

**To Reproduce**:
1. Log in
2. Open order list
3. Wait when the Cookie Lifetime ends
4. Open order

**Actual result**:
User redirects to Homepage BUT user can't scroll page

**Additional conteext**:
You can change Cookie Lifetime in Admin panel -> Stores -> General -> Web -> Cookie Lifetime
_____________________________

**2. Description**:
Mobile: User sees blank page ±3sec after logged in

**Expected behavior**:
My account appears after user logged in and blank page is missing if it's possible
If not -> Add loader icon 

**To Reproduce**:
1. Log in

**Actual result**:
User sees blank page ±3sec

**Additional context**:
Seems it happens because of cart takes a long time to load
__________________________________

**3. Description**:
User doesn't see notification message 'Your session is over, you are logged out!' if Cookie Lifetime ends and he opens 404 page

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed

**To Reproduce**:
1. Log in
2. Wait when the Cookie Lifetime ends
3. Open not existing page (404)

**Actual result**:
The notification message 'Your session is over, you are logged out!' is missing

__________________________________

**4. Description**:
User stays on the shipping step if Cookie Lifetime ends

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed and user redirects to /account/login
Also do the same if user located on my account pages

**To Reproduce**:
1. Log in
2. Add product to cart
3. Go to shipping step
4. Fill form
5. Wait when the Cookie Lifetime ends
6. Go to billing step

**Actual result**:
User stays on the shipping step. All products are missing 
![image](https://user-images.githubusercontent.com/73526235/116546242-0e4ab700-a8fa-11eb-8af7-2a6e9b99d660.png)

**Additional context**:
If user tried to fill form, ooops page opens
![image](https://user-images.githubusercontent.com/73526235/116547167-38e93f80-a8fb-11eb-94e6-a158d2dcfb4f.png)

__________________________________

**5. Description**:
Error message 'Current user isn't authorized' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user changes password

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed and user redirects to /account/login

**To Reproduce**:
1. Log in
2. Open my account
3. Click change password
4. Wait when the Cookie Lifetime ends
5. Enter current and new password
6. Click change password

**Actual result**:
Error message 'Current user isn't authorized' is displayed and user stays on the same page in my account
![image](https://user-images.githubusercontent.com/73526235/116553866-40144b80-a903-11eb-8972-3c28894a945c.png)

**Additional context**:
Steps:
Close change password pup up
Open Edit details
Change
Click Save 
=> user redirects to homepage -> can't scroll page

__________________________________

**6. Description**:
Error message 'Authorization unsuccessful' is displayed and user stays on the same page in my account if Cookie Lifetime ends and user shares wishlist

**Expected behavior**:
The notification message 'Your session is over, you are logged out!' is displayed and user redirects to /account/login

**To Reproduce**:
1. Log in
2. Add product to Wishlist
3. Open Wishlist
4. Click Share Wishlist
5. Enter email
6. Wait when the Cookie Lifetime ends
7. Clips send

**Actual result**:
Error message 'Authorization unsuccessful' is displayed and user stays on the same page in my account
![image](https://user-images.githubusercontent.com/73526235/116554457-e1030680-a903-11eb-8925-0c7763f90d88.png)

__________________________________

**7. Description**:
guest_quote_id disappears if not logged in user completed order

**Expected behavior**:
Product is added to cart

**To Reproduce**:
1. Add product to card
2. Complete order

**Actual result**:
guest_quote_id disappears
User can't add product to cart
Token appears when refreshing page 

**Additional context**:
If user logged in and complete order -> guest_quote_id chenges
__________________________________

**8. Description**:
Sometimes logged user sees error message 'Internal server error' when adding product to cart
I didn’t find specific steps to reproduce it. If user logged out , he can add product to cart

**Comment by zans-laksa** [comment] 2021-05-06 00:20
> 3. User doesn't see notification message 'Your session is over, you are logged out!' if Cookie Lifetime ends and he opens 404 page

User does see the notification, if he is followed by a link. User doesn't see notification, if page is loaded by url or reloaded, since redux doesn't have any value about whether user was authenticated before. This behavior is on every page, not on 404 only.

> 8. Sometimes logged user sees error message 'Internal server error' when adding product to cart
I didn’t find specific steps to reproduce it. If user logged out , he can add product to cart.

Cannot reproduce. Likely have fixed with other issues.

**Closed** 2021-05-11 14:56 UTC
Labels: Core, Status: Waiting Estimate, Type: QA BUG
