### ISSUE TITLE
Category image is 'Not found image' on category page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1531] opened 2020-10-28 10:07 UTC
**Description**:
Category image is missing on category page

**Expected behavior**:
Category image is displayed

**Screenshots, Video, Logs**
![Screenshot 2020-10-28 at 12 05 37](https://user-images.githubusercontent.com/73526235/97422056-f4fa8b00-1915-11eb-93f1-20c71e9ce503.png)

**To Reproduce**:
1. Open category page

**Versions**:
Category image is missing on category page

**Additional context**:

**Comment by lianastaskevica** [comment] 2020-11-17 10:49
The issue is that there is an image added in the Magento BE to this category that was not uploaded to the server. 
<img width="1440" alt="Screenshot 2020-11-17 at 12 48 16" src="https://user-images.githubusercontent.com/52198221/99380849-2a6e1500-28d3-11eb-8f65-b520d4ee17a4.png">
<img width="1349" alt="Screenshot 2020-11-17 at 12 48 25" src="https://user-images.githubusercontent.com/52198221/99380874-2fcb5f80-28d3-11eb-850a-29757ed4777b.png">

When deleting the image from BE, everything is ok. 
<img width="1070" alt="Screenshot 2020-11-17 at 12 48 58" src="https://user-images.githubusercontent.com/52198221/99380930-440f5c80-28d3-11eb-978f-d44282e19837.png">

Closing as cannot reproduce.

**Comment by AleksandrsKondratjevs** [comment] 2020-12-11 15:46
Issue appears when using multi-store. Graphql sends image url with storecode included into path:
https://scandipwa.local/default/media/catalog/category/womens_jackets_1.jpg

should be without it:
https://scandipwa.local/media/catalog/category/womens_jackets_1.jpg

**Closed** 2020-12-28 14:04 UTC
Labels: Core, Status: Failed CR, Type: bug
