### ISSUE TITLE
Tech demo: internal server error on PLP

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3352] opened 2021-09-20 10:33 UTC
**To Reproduce**:
1. Go to https://tech-demo.scandipwa.com/tech_storeview/smartphones-gadgets.html?customFilters=brands:215616;category_id:839;cl_smartphones_processor___294:298156;color_palette:322391;price:1470_1479.99

**Result:** Products don't load. Error in response:
```
{"errors":[{"message":"Internal server error","extensions":{"category":"internal"},"path":["products"]}],"data":{"products":null}}
```

Error from server logs:
```
[2021-09-20 19:49:52] main.ERROR: Can't check requested quantity for products without Source Items support. {"exception":"[object] (GraphQL\\Error\\Error(code: 0): Can't check requested quantity for products without Source Items support. at /home/tappiola/PhpstormProjects/readymage-tech-demo/vendor/webonyx/graphql-php/src/Error/Error.php:174, Magento\\Framework\\Exception\\InputException(code: 0): Can't check requested quantity for products without Source Items support. at /home/tappiola/PhpstormProjects/readymage-tech-demo/vendor/magento/module-inventory-sales/Model/GetProductSalableQty.php:109)"} []
```

**Expected result:**
Products load.

**Comment by tatiana-scandi** [comment] 2021-09-20 20:27
Fixed by removing broken data from DB. The faulty product was not even searchable (and consequently not deletable) via Magento admin.

Faulty product:
![photo_2021-09-20_21-26-46](https://user-images.githubusercontent.com/79456428/134070738-6378f620-cd24-4b61-8816-6db4c2fdcfe6.jpg)

**Comment by carinadues** [comment] 2021-12-31 11:58
Closing as the issue is fixed.

**Closed by carinadues** 2021-12-31 11:58 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, BE
