### ISSUE TITLE
Specific products don't have price on PLP and PDP

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2734] opened 2021-06-08 11:10 UTC
**Description**:
Specific products don't have price on PLP and PDP

**Expected behavior**:
Prices are displayed

**To Reproduce**:
1. Open https://scandipwapmrev.indvp.com/default/women?page=4
2. Open https://scandipwapmrev.indvp.com/default/n-slim-fit-jeans.html

**Actual result**:
Product doesn't have price on PLP and PDP
![image](https://user-images.githubusercontent.com/73526235/121174756-edfc0980-c862-11eb-8896-ffd1f3d668b1.png)
![image](https://user-images.githubusercontent.com/73526235/121174761-f0f6fa00-c862-11eb-96b1-f5c4d3feaf36.png)

**Comment by tatiana-scandi** [comment] 2021-06-23 10:30
FE: https://github.com/scandipwa/scandipwa/pull/2806
BE: I investigated the issue and wanted to apply the fix by myself, but noticed the same fix was already done by contributor: https://github.com/scandipwa/performance/pull/19. I tested it locally, it helps to resolve the issue.

Behaviour after fix: 
- product is displayed as Out of stock, which is correct
- Label As low as is hidden for out of stock products (done for the following reasons: 1. Luma does it 2. it makes sense, as lowest price in not applicable, if all options are Out of stock) 3. this is default Magento behaviour to return 0 for minimum price, if all options are out of stock
- also disabled Add to cart button for Out of stock products

Asked Carina to confirm this is fine before implementing it like this.

**Comment by carinadues** [comment] 2021-06-29 15:12
Closing after merged pull 2806

**Comment by aleksandrakorolova** [comment] 2021-06-30 05:27
1. Price is missing on PLP but Product in stock and price is displayed on PDP 
**Products:**
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/women/n-sweat-pants.html
https://4-4-1-rc.d25kd40decjpue.amplifyapp.com/default/women/n-business-trousers.html

2. Price disappears when selecting one attribute value. Price appears when selecting all attributes

**Video for 1 and 2 issues:**
 https://drive.google.com/file/d/1g96GsFsw2aeJYJ1Yu_ymKX9yH9-CXqK6/view?usp=sharing

3. Button Add to cart is active for out of stock products
![Screenshot 2021-06-30 at 08 23 22](https://user-images.githubusercontent.com/73526235/123906321-9f7eee00-d97c-11eb-8364-6e29c8b222a3.png)

**Comment by carinadues** [comment] 2021-06-30 21:40
I couldn't reproduce issues 1 and 3. Can you check, @aleksandrakorolova?

**1:**

![image](https://user-images.githubusercontent.com/82165392/124035029-578ab600-d9d2-11eb-9f6e-b531d28c4cac.png)

**3:** 

![image](https://user-images.githubusercontent.com/82165392/124035184-96207080-d9d2-11eb-9a2a-95a8901cb691.png)

**Comment by aleksandrakorolova** [comment] 2021-07-01 05:23
@carinadues 
1. I suppose your screenshot is taken on search result page and there price is displayed but still price is missing on PLP
![Screenshot 2021-07-01 at 08 13 20](https://user-images.githubusercontent.com/73526235/124069568-1089d880-da45-11eb-9b14-fabadbbcdf3d.png)

3.Also can't reproduce

**Comment by zans-laksa** [comment] 2021-07-03 02:36
On PDP prices disappeared because partially filled attributes matched multiple product variants. But the first one was selected, regardless of it's stock status.
On PLP prices are disappeared for the same reason, except that only first one variant is fetched from the graphql, regardless of it's stock status.
Will fix the PLP on Monday.

**Closed** 2021-07-05 09:14 UTC
Labels: Core, Status: Failed QA, Type: bug
