### ISSUE TITLE
Uncaught TypeError in the browser's console when user double clicks on product's image

### ISSUE THREAD

**Issue by denissfedutins** [scandipwa/scandipwa#961] opened 2020-09-10 08:59 UTC
**Description**:
When the user navigates to the PDP and double clicks on the product's image, numerous Uncaught TypeErrors are shown in the browser's console log.
When the first Uncaught TypeError is shown in the console, the user double clicks again and the product's image is zoomed in. In zoomed in image double clicks do not trigger any errors in the console. After the user zooms out the image and double clicks again, no zoom happens and another Uncaught TypeError is triggered in the console.

**Expected behavior**:
User double clicks on the product's image and there are no errors in the browser's console and the image is zoomed in successfully.

**Screenshots, Video, Logs**
https://www.screencast.com/t/aTeUU87qMe

**To Reproduce**:
1. Go to store's FE
2. Navigate to whatever PDP
3. Open browser console
4. Double click on the product's image
5. See the error in the console
6. Double click on the product's image
7. Image is zoomed in
8. Zoom out
9. Repeat steps 4-8

**Versions**:
- Chrome Version 85.0.4183.102 (Official Build) (64-bit)
- MacOS Sierra 10.12.6 

**Additional context**:
The same problem occurred in the project which is built on the ScandiPWA.

**Comment by aleksandrakorolova** [comment] 2021-01-14 14:10
Closing as cannot reproduce
You can see it on demo website
https://drive.google.com/file/d/1nVj7ai5VTc5-kohAtFhw79nnuc1Tq8kO/view?usp=sharing

**Closed by aleksandrakorolova** 2021-01-14 14:10 UTC
Labels: Core, Estimate: <1, Type: bug
