### ISSUE TITLE
Mobile: Share wishlist button disappears after reloading the page

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#4617] opened 2022-03-29 20:39 UTC
**Description**:
The share wishlist button disappears after reloading the page on mobile.

**Expected behavior**:
When the wishlist has items added to it, the button won't disappear after the user reloads.

**Actual result**
Now, if the wishlist has items and the user reloads the page, the icon will go missing.

**To Reproduce**:

1. Open the wishlist with products 
2. Reload the tab

**Video**:
https://user-images.githubusercontent.com/82165392/160701534-6f08adb3-0ab7-43fa-9cfb-4ef248b79839.MP4

**Additional context**:
Tested on Safari, iOS

**Comment by aleksandrakorolova** [comment] 2022-03-30 04:47
Closed because duplicate of #3012

**Closed by aleksandrakorolova** 2022-03-30 04:47 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
