### ISSUE TITLE
Success message appears when entering not registered email in forgot password form

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#1847] opened 2020-12-08 10:38 UTC
**Description**:
Success message appears when entering not registered email in forgot password form

**Expected behavior**:
Error message 'This email does not exist.' appears 

**To Reproduce**:
1. Open website
2. Tap forgot password
3. Enter NOT registered email
4. Tap send

**Actual result**:
Success message 'If there is an account associated with the provided address you will receive an email with a link to reset your password.' is displayed

**Additional context**:

**Comment by krelo** [comment] 2020-12-23 07:57
Seems to work as intended. It does say 'If there is an accout...'
This is standard practice as to not give any information about registered users.

**Comment by lianastaskevica** [comment] 2020-12-23 17:19
Closing as this is the expected behavior

**Closed by lianastaskevica** 2020-12-23 17:19 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
