### ISSUE TITLE
Oops page if the attribute is set to not used in product listing

### ISSUE THREAD

**Issue by lianastaskevica** [scandipwa/scandipwa#2070] opened 2021-01-11 11:51 UTC
**Description**:
Oops page if the attribute that is used in the product configurations is set to not used in product listing

**Expected behavior**:
No oops page appears. This attribute is not used in the option preview on the product cards.

**To Reproduce**:
1. Open the attribute in edit mode in admin. (make sure you have some config products that use this attribute in their configurations, e.g. color)
2. make sure the "used in product listing" option is set to no
3. Save and flush cache
4. Open config product on FE
5. Notice oops page

**Versions**:
ScandiPWA v4

**Comment by aleksandrakorolova** [comment] 2021-01-11 13:49
Closing as a duplicate of #1996

**Closed by aleksandrakorolova** 2021-01-11 13:49 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
