### ISSUE TITLE
Blank page opens instead of 404 page 

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#4608] opened 2022-03-29 08:28 UTC
**Description**:
Blank page opens instead of 404 page 

**Expected behavior**:
404 page opens 

**To Reproduce**:
1. Open not existing page - https://master.d25kd40decjpue.amplifyapp.com/default/sfdsfdsf

**Actual result**:
Blank page opens
![Screenshot 2022-03-29 at 11 35 13](https://user-images.githubusercontent.com/73526235/160569584-44b43747-6bca-4abf-8707-c330486ff2f4.png)

**Comment by VanilStorm** [comment] 2022-03-30 10:14
I can't reproduce, in local and production( https://scandipwapmrev.indvp.com/asFagdsa ) app, everything works fine.

**Comment by aleksandrakorolova** [comment] 2022-03-30 11:36
Did you open link from steps?

**Comment by VanilStorm** [comment] 2022-03-30 11:59
Of course, but I can't reproduce it in the local application. 
<img width="1440" alt="Снимок экрана 2022-03-30 в 14 58 08" src="https://user-images.githubusercontent.com/77737846/160829354-62409e03-1f62-4002-812c-a72479a49af0.png">

**Comment by AzizKHAN030** [comment] 2022-05-18 08:40
I think this issue has been resolved by another PR and now I can't reproduce it either in pmrev or in master

**Comment by carinadues** [comment] 2022-05-19 22:24
I also get a 404 from opening the link. @aleksandrakorolova can you please check and close if it is fixed?

**Closed** 2022-05-20 06:08 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
