### ISSUE TITLE
Category filter styling breaks with Magento default sample data

### ISSUE THREAD

**Issue by iamrolands** [scandipwa/scandipwa#2135] opened 2021-01-28 14:00 UTC
**Description**:
Category filter takes swatchlist class instead of dropdown-list class therefore styling breaks.

**Expected behavior**:
Category filters is styled with dropdown list styles.

**Screenshots, Video, Logs**
<img width="515" alt="Screen Shot 2021-01-27 at 15 16 11" src="https://user-images.githubusercontent.com/18136951/106148449-b927c980-6181-11eb-8378-a5602d15dc88.png">

**To Reproduce**:
1. Import default Magento sample data.
2. Open category on the frontend.

**Versions**:
- ScandiPWA: 4.0.0

**Comment by riha112** [comment] 2021-03-09 09:25
**Unable to reproduce** 

Swatch data is assign to attribute only if attributes itself is marked as "swatch type", you can check if it's marked from DB in table ```catalog_eav_attribute``` field ```additional_data``` _(If you wish to unassigne it from swatch type you can delete corresponding data)_ _(by default it should be empty for category_ids attribute)_. 

Also returns that are visible within graphql response shows values that Magento 2 sample data module is not creating within ```eav_attribute_option_swatch``` table (_so most likely your DB already contained some modifications that are not related to sample data module itself_).

**Closed** 2021-03-09 14:40 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
