### ISSUE TITLE
When sku is in uppercase, product page is not fully loading

### ISSUE THREAD

**Issue by devselegento** [scandipwa/scandipwa#2171] opened 2021-02-05 09:59 UTC
**Description**:
When product sku is in uppercase (e.g. TEST-PRODUCT-SKU) then product page is not fully loading. The name and price is showing correctly but breadcrumb and attributes are having the loading indicator

**Versions**:
- ScandiPWA: 4.0.1

**Comment by lianastaskevica** [comment] 2021-02-09 15:54
Hello @devselegento! Cannot reproduce the issue on the ScandiPWA v4.0.2 -> https://prnt.sc/yuyy8n. Can you please update the version and retest if the issue is still present for you? Closing the issue for now.

**Closed by lianastaskevica** 2021-02-09 15:54 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
