### ISSUE TITLE
Blank order pop up is displayed on my orders page

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2186] opened 2021-02-10 13:05 UTC
**Description**:
Blank order pop up is displayed on my orders page

**Expected behavior**:
Order pop up with all data is displayed

**To Reproduce**:
1. Log in
2. Open order list
3. Open order popup (if user doesn't have order history - complete order)

**Actual result**:
Blank pop up opens
![image](https://user-images.githubusercontent.com/73526235/107513327-bd57dc00-6bb0-11eb-8d59-c3fee2ae42a1.png)

**Comment by winniepukki** [comment] 2021-02-11 10:12
@alfredsgenkins @aleksandrakorolova could you please clear all server caches, since [the following](https://github.com/scandipwa/quote-graphql/pull/57) PR should fix this issue. I lack access permissions

**Comment by lianastaskevica** [comment] 2021-02-25 13:17
Cannot reproduce the task anymore. Closing.

**Closed by lianastaskevica** 2021-02-25 13:17 UTC
Labels: Core, Status: Waiting Estimate, Type: QA BUG
