### ISSUE TITLE
Add Print Order button in My Orders page

### ISSUE THREAD

**Issue by carinadues** [scandipwa/scandipwa#2502] opened 2021-04-15 11:09 UTC
**Description**:
Add Print Order button in My Orders page as default Magento 2.

**Additional context**:

![image](https://user-images.githubusercontent.com/82165392/114859970-cee07e80-9dc1-11eb-9cb4-5fe38581f6f6.png)

**Comment by aleksandrakorolova** [comment] 2022-02-28 12:03
Duplicate of #3751

**Closed by aleksandrakorolova** 2022-02-28 12:03 UTC
Labels: Type: feature, Core, Status: Waiting Estimate
