### ISSUE TITLE
Never ending loader if selected filter combination returned no results

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2797] opened 2021-06-18 12:11 UTC
**Description**:
Never ending loader if selected filter combination returned no results

**Expected behavior**:
Text 'The selected filter combination returned no results. Please try again, using a different set of filters.' is displayed/ User can click on Reset button.

**To Reproduce**:
1. Open category - https://master.d25kd40decjpue.amplifyapp.com/default/accessories/accessories-bags/handbags.html
2. Select filter by color
3. Select filter by price

**Actual result**:
Never ending loader 
![Screenshot 2021-06-18 at 15 07 36](https://user-images.githubusercontent.com/73526235/122559056-7dfe3800-d047-11eb-897d-cec3890c3b0f.png)

**Additional context**:

**Comment by riha112** [comment] 2021-08-17 08:10
Unable to reproduce

**Comment by carinadues** [comment] 2021-08-30 11:19
I'm closing this issue as I was also unable to reproduce.

**Closed by carinadues** 2021-08-30 11:19 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, Area: PLP, Unable to reproduce
