### ISSUE TITLE
Duplicate title is displayed on PDP if user opened downloadable product from wishlist

### ISSUE THREAD

**Issue by aleksandrakorolova** [scandipwa/scandipwa#2810] opened 2021-06-28 12:04 UTC
**Description**:
Duplicate title is displayed on PDP if user opened downloadable product from wishlist

**Expected behavior**:
No duplicate
![Screenshot 2021-06-28 at 15 04 24](https://user-images.githubusercontent.com/73526235/123633676-28cddd80-d822-11eb-8b40-7e242fab3441.png)

**To Reproduce**:
1. Open FE
2. Log in
3. Add downloadable product to Wishlist
4. Open Wishlist
5. Open this downloadable product

**Actual result**:
Duplicate title is displayed
![Screenshot 2021-06-28 at 14 58 09](https://user-images.githubusercontent.com/73526235/123633349-c248bf80-d821-11eb-828d-5b2009e40b26.png)

**Comment by winniepukki** [comment] 2021-06-29 18:09
@aleksandrakorolova unable to reproduce

**Comment by carinadues** [comment] 2021-07-14 14:47
Closed because can't reproduce anymore.

**Comment by aleksandrakorolova** [comment] 2021-07-15 12:49
Can reproduce if open downloadable product via wishlist and the refresh page
https://drive.google.com/file/d/1KbpGzFSyiws9Yg6MYI-6Cft4C265bEr9/view?usp=sharing

**Comment by winniepukki** [comment] 2021-07-15 14:41
@aleksandrakorolova, have you assured the issue persists at the redesigned branch?

**Comment by carinadues** [comment] 2021-07-16 20:22
Tested for the redesign branch and if you refresh the page the issue happens. 
Tested with these products:
https://theme-redesign.d25kd40decjpue.amplifyapp.com/default/downloadable-print-for-bag.html
https://theme-redesign.d25kd40decjpue.amplifyapp.com/default/downloadable.html

**Comment by carinadues** [comment] 2021-07-29 12:52
This issue was fixed in https://github.com/scandipwa/scandipwa/issues/2977

**Closed by carinadues** 2021-07-29 12:52 UTC
Labels: Core, Status: Waiting Estimate, Type: bug
