### ISSUE TITLE
Error message 'Minimum 8 characters!' is displayed when user try to submit empty form in 'Create account' popup

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#3884] opened 2021-12-07 14:59 UTC
**Description**:
Error message 'Minimum 8 characters!' is displayed when user try to submit empty form in 'Create account' popup
Same on Create account page

**Expected behavior**:
Only  'This field is required' is displayed when user try to submit empty form in 'Create account' popup

**Screenshots, Video, Logs**
![image](https://user-images.githubusercontent.com/84388061/145052448-7bb2449d-b127-41e5-8a02-545c1cff5dda.png)

**To Reproduce**:
1. Open home page
2. Click on Account sign > Create  account > Sign up

**Actual result**:
Error message 'Minimum 8 characters!' is displayed when user try to submit empty form in 'Create account' popup

**Comment by aleksandrakorolova** [comment] 2021-12-08 05:26
Duplicate of #3687

**Closed by aleksandrakorolova** 2021-12-08 05:26 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, Area: Sign In
