### ISSUE TITLE
Write a review buttons absent on PDP

### ISSUE THREAD

**Issue by Elena-Evsa** [scandipwa/scandipwa#4357] opened 2022-02-28 13:55 UTC
**Description**:
Write a review buttons absent on PDP

**Expected behavior**:
Write a review buttons present on PDP same as on pmrev (under title and in Review tab)

**Screenshots, Video, Logs**
https://vimeo.com/682846904/f66e7ed805

**To Reproduce**:
1. Open any PDP

**Actual result**:
Write a review buttons absent on PDP

**Comment by pablobentivengo** [comment] 2022-02-28 14:29
Hey! Was checking there is an option in BE to disable reviews. I think they are disabled.

Image is from local setup
![image](https://user-images.githubusercontent.com/97158749/156000088-6c28c6e3-c58b-40c7-a31f-d8101ab082dd.png)

**Comment by Elena-Evsa** [comment] 2022-03-01 09:26
On screenshot (and video) shown that reviews enabled. Setting set to 'yes'

**Comment by carinadues** [comment] 2022-03-02 12:19
Closing because I couldn't reproduce.

**Closed by carinadues** 2022-03-02 12:19 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, Area: PDP
