### ISSUE TITLE
Scandi 5.x Language switcher show all store_views and not only current website store_views

### ISSUE THREAD

**Issue by romeof1980** [scandipwa/scandipwa#3831] opened 2021-11-30 09:56 UTC
**Prerequisites**:
ScandiPWA 5.0.4
Magento 2.4.3

**Description**:
Scandi 5.x Language switcher show all store_views and not only current website store_views

**To Reproduce**:
Create 3 website and 2 (or more) store_view per website:
- Website Canada (Canadian Dollars) with store_view English (ca_en) and French (ca_fr)
- Website USA (US Dollars) with store_view English (us_en) and Spanish (us_es)
- Website Switzerland (Suisse Franc) with store_view French (ch_fr), Italian (ch_it) and German (ch_de)

**Expected behavior**:
- Accessing Canada Website I expect to see language switcher to give me [only] the possibility to switch between ca_en and ca_fr store_view.
- Accessing USA Website I expect to see language switcher to give me [only] the possibility to switch between us_en and us_es store_view.
- - Accessing Switzerland Website I expect to see language switcher to give me [only] the possibility to switch between ch_fr, ch_it and de_de store_view.

**Actual results**:
any website show every store_view in the language switcher: for example Canadian Website also show Switzerland store_views in the language switcher. Of course hat is not what happens in Magento when using Luma.
This happens because the language switcher component/container call the list of all application store_views without filtering by CURRENT WEBSITE.

**Versions**:
- "@scandipwa/scandipwa": "5.0.4"
- Magento 2.4.3

**Additional context**:
Magento Multisite (in order to manage different currencies) and multistore (in order to manage different languages for the same currency). That is magento standard

**Comment by aleksandrakorolova** [comment] 2021-12-03 15:03
Duplicate of #2639

**Closed** 2021-12-03 17:57 UTC
Labels: Type: bug, Core, Status: Waiting Estimate
