### ISSUE TITLE
Configurable product is added to wishlist incorrectly

### ISSUE THREAD

**Issue by tatiana-scandi** [scandipwa/scandipwa#3481] opened 2021-10-05 14:16 UTC
**To Reproduce**:
1. Go to https://master.d25kd40decjpue.amplifyapp.com/default/configurable-shorts.html
2. Select XL, Black
3. Click Add to wishlist
4. Go to wishlist

**Result:**
- Wrong picture is displayed (should be black shorts, not orange)
- No info on what product configuration selected (should be XL, Black label on product card)
![ScandiPWA 2021-10-05 15-12-02](https://user-images.githubusercontent.com/79456428/136040350-f5e5f885-5fb7-4aff-b1e9-df9289b1cddb.png)

Which is a consequence of selected configuration data not being saved correctly:
<img width="1143" alt="DBeaver 21 1 1 - wishlist_item_option 2021-10-05 15-14-00" src="https://user-images.githubusercontent.com/79456428/136040941-6f17aff1-5ff1-4eba-a706-588d8b8dcf51.png">

**Comment by AleksandrsKondratjevs** [comment] 2021-11-02 07:18
Can't reproduce.

**Comment by AleksandrsKondratjevs** [comment] 2021-11-02 07:29
Will close it. If at chance that it will be still reproducible issue will be reopened.

**Closed by AleksandrsKondratjevs** 2021-11-02 07:29 UTC
Labels: Type: bug, Core, Status: Waiting Estimate, Area: Wishlist
